<a href="https://colab.research.google.com/github/idelahoussay2022/Stat-Class/blob/main/Delahoussaye_Lab_3_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [332]:
for i in range(1000):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [333]:
from IPython.core.display import display, HTML


In [334]:
for i in range(5,8):
  print(i)

5
6
7


In [335]:
for i in range(3):
  print("test number:", i)

test number: 0
test number: 1
test number: 2


In [336]:
def square(x):
    return x**2

In [337]:
square(5)

25

In [338]:
square(100)

10000

In [339]:
square(square (100))


100000000

In [340]:
square(square(square(square(square(square(100))))))

100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

In [341]:
def add_two(x):
    return x+2

In [342]:
add_two(5)

7

Logical Branching

In [343]:
choice = "apple"

In [344]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You choose apples.


In [345]:
choice = "orange"

In [346]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You did not choose apples.


In [347]:
if choice == "apple":

    print("You choose apples.")
    print("Thank you, shop again")

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again")

You choose oranges.
Thank you, shop again


User imput

In [348]:
choice = input("Please enter your choice (i.e. apple): ")

Please enter your choice (i.e. apple): peach


In [349]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")
    

You did not choose apples or oranges.


In [350]:
import numpy as np

In [351]:
np.random.permutation(52)

array([49, 22, 11,  6, 47,  4,  8, 12, 34, 16, 50, 45, 51,  2, 48, 20, 17,
       31, 39, 13, 26, 36, 28, 27, 42, 14, 19, 43, 15, 25, 18, 40, 23,  0,
       35, 38, 44, 10, 32, 30, 29, 21, 33,  9, 41, 37, 24,  3, 46,  1,  5,
        7])

Cards

In [352]:
cards = np.random.permutation(52)


<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>


In [353]:
np.arange(52).reshape(4,13)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [354]:
np.arange(52).reshape(4,13)%13


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [355]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [356]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [357]:
def card_name(card_number):
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [358]:
cards = np.random.permutation(52)

In [359]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [360]:
top_of_deck,second_card_in_deck,last_card_in_deck

('Five of Spades', 'Eight of Spades', 'Queen of Spades')

In [361]:
for i in range(15):
    print(card_name(cards[i]))
  

Five of Spades
Eight of Spades
Two of Clubs
Eight of Hearts
Four of Diamonds
Six of Clubs
Ace of Spades
Three of Clubs
Two of Hearts
Six of Spades
Four of Clubs
Queen of Clubs
King of Diamonds
Jack of Clubs
Four of Hearts


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [362]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [363]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [364]:
i = np.random.randint(4)
j = np.random.randint(13)

In [365]:
suit[i]

's'

In [366]:
card[j]

'8'

In [367]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [368]:
img = card_url_head + suit[i]+card[j] + card_url_tail

In [369]:
show_img(img)

In [370]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [371]:
card_image(3)

'k4'

In [372]:
img = card_url_head + card_image(3) + card_url_tail

In [373]:
show_img(img)

In [375]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)