<a href="https://colab.research.google.com/github/idelahoussay2022/Stat-Class/blob/main/Delahoussaye_Lab_3_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
for i in range(1000):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

Prints all integers 0 through 100

In [2]:
from IPython.core.display import display, HTML


In [3]:
for i in range(5,8):
  print(i)

5
6
7


Displays number within set range

In [4]:
for i in range(3):
  print("test number:", i)

test number: 0
test number: 1
test number: 2


Displays number within set range while printing the words "test number" in front of the number

In [5]:
def square(x):
    return x**2

Defines squaring function

In [6]:
square(5)

25

test of above function

In [7]:
square(100)

10000

test of square fuction with a larger number

In [8]:
square(square (100))


100000000

Squares the square of the specified number

In [9]:
square(square(square(square(square(square(100))))))

100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

Amore layered version of the above line of code

In [10]:
def add_two(x):
    return x+2

Defining the function of adding 2 to an inputed number

In [11]:
add_two(5)

7

test of above fuction

Logical Branching

In [12]:
choice = "apple"

In [13]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You choose apples.


If else code to display one output, if the input matches what was programmed

In [14]:
choice = "orange"

In [15]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You did not choose apples.


If else code to display one output, if the input does not match what was programmed

In [16]:
if choice == "apple":

    print("You choose apples.")
    print("Thank you, shop again")

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again")

You choose oranges.
Thank you, shop again


Same as above with an extra option, added in as well as the message "thank you shop again" after

User imput

In [17]:
choice = input("Please enter your choice (i.e. apple): ")

Please enter your choice (i.e. apple): peach


Allows you to input information to complete next line of code

In [18]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")
    

You did not choose apples or oranges.


Same if else code as above, but this time responding to user input

In [19]:
import numpy as np

In [20]:
np.random.permutation(52)

array([36, 11, 32, 50, 26, 20, 38, 35, 30, 40, 29, 39,  8, 42, 13, 43, 14,
       33, 47,  2,  5,  7, 22, 25, 41,  0, 17, 49, 51,  4, 19, 27, 18, 21,
       45, 28, 15, 12, 48, 46,  3, 24,  1, 34, 44, 10,  6, 16, 31,  9, 37,
       23])

odes in a deck of cards in the form of numbers between 0 and 52 

Cards

In [21]:
cards = np.random.permutation(52)


<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>


Codes in a deck of cards in the form of pictures of said cards in a deck

In [22]:
np.arange(52).reshape(4,13)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

Codes in a deck of cards in the form of numbers between 0 and 52 organized in rows 4 of 13 cards each

In [23]:
np.arange(52).reshape(4,13)%13


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [24]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

Divides the deck cards into its suits

In [25]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

Makes note of the four suits and the 13 numbers in a deck of cards

In [26]:
def card_name(card_number):
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

Telus computer, how to display a random card, pulled as car number of whatever suit

In [27]:
cards = np.random.permutation(52)

In [28]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

Defined numerical values for the card at the top of the deck, the second card in the deck and the card at the bottom of the deck

In [29]:
top_of_deck,second_card_in_deck,last_card_in_deck

('Two of Diamonds', 'King of Clubs', 'Three of Diamonds')

Computer "draws" the the first card at the second card at the last card in the deck

In [30]:
for i in range(15):
    print(card_name(cards[i]))
  

Two of Diamonds
King of Clubs
Seven of Clubs
Ten of Hearts
Five of Hearts
Jack of Hearts
Six of Hearts
Three of Hearts
Eight of Diamonds
Ten of Diamonds
Nine of Clubs
Six of Clubs
Two of Hearts
Ace of Diamonds
Six of Diamonds


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

Computer draws the first 15 cards

In [31]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [32]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

Short hand for each suit, and each number of card

In [33]:
i = np.random.randint(4)
j = np.random.randint(13)

In [34]:
suit[i]

's'

In [35]:
card[j]

'2'

In [36]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [37]:
img = card_url_head + suit[i]+card[j] + card_url_tail

In [38]:
show_img(img)

Card at top of the deck in picture form

In [39]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

 Display card name in shorthand form

In [44]:
card_image(3)

'k4'

Computer "draws" the third card from the top out of the deck

In [41]:
img = card_url_head + card_image(3) + card_url_tail

In [42]:
show_img(img)

Image of third card from top of deck

In [43]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)

Computer displays entire deck of cards sorted by suit